import { PlanLimits, PlanName } from "../types/plan-limits";

export const PLAN_LIMITS: Record<PlanName, PlanLimits> = {
    starter: {
        links: 5,
        menu: 3,
        items_per_category: 3,
        faq: 3,
        success_story: false,
        events: 2,
        gallery: 10,
        automaticEmail: true,
        whiteLabelEmail: false,
        popups: 0,
        analyticsRetention: { type: 'days', value: 7 },
        qrCodes: 3,

        appearance: 'Full',
        reviews: false,
        customDomain: false,
        mobileReady: true,
        orderSystem: false,
        reservations: false,
        zeroCommission: false,
        crossVenueRapportage: false,
        venues: 1,
        ssoRoleBased: false,
        supportChannel: 'email',
        whiteLabelBranding: false,
        installationOnboarding: false,
        accountManager: false,
        googleBusiness: false,
        googleSheets: false,
        metaPixel: false,
        lightspeed: false,
        deliverect: false,
    },
    growth: {
        links: 10,
        menu: 8,
        items_per_category: 5,
        faq: 'unlimited',
        success_story: true,
        events: 10,
        gallery: 30,
        automaticEmail: true,
        whiteLabelEmail: false,
        popups: 3,
        analyticsRetention: { type: 'days', value: 90 },
        qrCodes: 10,

        appearance: 'Full',
        reviews: true,
        customDomain: false,
        mobileReady: true,
        orderSystem: true,
        reservations: true,
        zeroCommission: true,
        crossVenueRapportage: true,
        venues: 1,
        ssoRoleBased: false,
        supportChannel: 'whatsapp',
        whiteLabelBranding: false,
        installationOnboarding: false,
        accountManager: false,
        googleBusiness: true,
        googleSheets: true,
        metaPixel: false,
        lightspeed: true,
        deliverect: true,
    },
    scale: {
        links: 'unlimited',
        menu: "unlimited",
        items_per_category: "unlimited",
        faq: 'unlimited',
        success_story: true,
        events: 'unlimited',
        gallery: 'unlimited',
        automaticEmail: true,
        whiteLabelEmail: true,
        popups: 5,
        analyticsRetention: { type: 'days', value: 365 },
        qrCodes: 'unlimited',

        appearance: 'Brand kit',
        reviews: true,
        customDomain: true,
        mobileReady: true,
        orderSystem: true,
        reservations: true,
        zeroCommission: true,
        crossVenueRapportage: true,
        venues: 'unlimited',
        ssoRoleBased: true,
        supportChannel: 'phone',
        whiteLabelBranding: true,
        installationOnboarding: true,
        accountManager: true,
        googleBusiness: true,
        googleSheets: true,
        metaPixel: true,
        lightspeed: true,
        deliverect: true,
    },
} as const;