export const RESERVED_SLUGS: ReadonlySet<string> = new Set([
  "about",
  "admin",
  "api",
  "careers",
  "cookies",
  "dashboard",
  "demo",
  "docs",
  "faq",
  "features",
  "forgot-password",
  "help",
  "onboarding",
  "order",
  "preview",
  "pricing",
  "privacy",
  "qr",
  "r",
  "reservation",
  "reset-password",
  "sign-in",
  "sign-up",
  "start",
  "terms",
  "verify",
  "_next",
  "_vercel",
  "assets",
  "fonts",
  "images",
  "public",
  "static",
  "app",
  "blog",
  "login",
  "logout",
  "mail",
  "register",
  "settings",
  "status",
  "support",
  "www",
]);

export const isReservedSlug = (slug: string): boolean => RESERVED_SLUGS.has(slug.toLowerCase());

export const SLUG_PATTERN = /^[a-z0-9]+(?:-[a-z0-9]+)*$/;

export const isValidSlugShape = (slug: string): boolean => SLUG_PATTERN.test(slug);
