import { AppearanceSettings, DEFAULT_APPEARANCE } from "@/lib/types/appearnace";

const createTemplate = (overrides: Partial<AppearanceSettings>): AppearanceSettings => ({
  ...DEFAULT_APPEARANCE,
  ...overrides,
});

export const TEMPLATES = [
  {
    id: "maitre-hero",
    name: "Maître",
    description: "Fine-dining photo hero with a frosted glass menu and champagne-gold accents.",
    settings: createTemplate({
      header_layout: "banner",
      cover_image: "https://images.unsplash.com/photo-1544025162-d76694265947?w=1600&q=80",
      bg_style: "image",
      bg_image: "https://images.unsplash.com/photo-1544025162-d76694265947?w=1600&q=80",
      bg_image_opacity: 0.72,
      heading_color: "#ffffff",
      text_color: "#ded8cf",
      fontFamily: "manrope",
      alternative_title_font: "playfair",
      sectionHeaderFontSize: 25,
      sectionHeaderFontWeight: 600,
      // Frosted glass panels with soft depth
      glassBlur: 12,
      sectionShadow: "soft",
      buttonShadow: "medium",
      sectionStyle: "solid",
      sectionShape: "pill",
      sectionBgColor: "#ffffff14",
      sectionBgColorTo: "#ffffff14",
      sectionBorderColor: "#ffffff2b",
      sectionRadiusPx: 18,
      sectionPaddingX: 22,
      sectionPaddingY: 18,
      sectionItemHeadingColor: "#ffffff",
      sectionItemTextColor: "#ded8cf",
      sectionItemHeadingFontSize: 15,
      sectionItemHeadingFontWeight: 600,
      sectionItemTextFontSize: 13,
      sectionItemTextFontWeight: 400,
      sectionIconBgColor: "#e3c27e",
      sectionIconColor: "#1f1600",
      sectionIconBorderColor: "#e3c27e",
      sectionIconRadiusPx: 12,
      sectionInIconBgColor: "#ffffff14",
      sectionInIconColor: "#e3c27e",
      sectionInIconBorderColor: "#ffffff2b",
      sectionInIconRadiusPx: 10,
      // Frosted glass buttons that fill with the accent on hover
      buttonStyle: "solid",
      buttonShape: "pill",
      buttonBgColor: "#ffffff1a",
      buttonBgColorTo: "#ffffff0d",
      buttonTextColor: "#ffffff",
      buttonBorderColor: "#ffffff33",
      buttonHoverBgColor: "#e3c27e",
      buttonHoverTextColor: "#1f1600",
      buttonHoverBorderColor: "#e3c27e",
      buttonRadiusPx: 16,
      buttonFontSize: 15,
      buttonFontWeight: 600,
      buttonPaddingX: 15,
      buttonPaddingY: 15,
      iconBgColor: "#ffffff1f",
      iconColor: "#e3c27e",
      iconBorderColor: "#ffffff33",
      iconRadiusPx: 12,
      profilePicRadius: 999,
    }),
  },
  {
    id: "lumiere-hero",
    name: "Lumière",
    description: "Bright, airy brunch hero with soft coral accents and frosted glass links.",
    settings: createTemplate({
      header_layout: "banner",
      cover_image: "https://images.unsplash.com/photo-1565299507177-b0ac66763828?w=1600&q=80",
      bg_style: "image",
      bg_image: "https://images.unsplash.com/photo-1565299507177-b0ac66763828?w=1600&q=80",
      bg_image_opacity: 0.55,
      heading_color: "#ffffff",
      text_color: "#f0e9e4",
      fontFamily: "manrope",
      sectionHeaderFontSize: 24,
      sectionHeaderFontWeight: 600,
      // Frosted glass panels with soft depth
      glassBlur: 12,
      sectionShadow: "soft",
      buttonShadow: "medium",
      sectionStyle: "solid",
      sectionShape: "rounded",
      sectionBgColor: "#ffffff14",
      sectionBgColorTo: "#ffffff14",
      sectionBorderColor: "#ffffff2b",
      sectionRadiusPx: 18,
      sectionPaddingX: 22,
      sectionPaddingY: 18,
      sectionItemHeadingColor: "#ffffff",
      sectionItemTextColor: "#f0e9e4",
      sectionItemHeadingFontSize: 15,
      sectionItemHeadingFontWeight: 600,
      sectionItemTextFontSize: 13,
      sectionItemTextFontWeight: 400,
      sectionIconBgColor: "#ff8f6b",
      sectionIconColor: "#2a0f06",
      sectionIconBorderColor: "#ff8f6b",
      sectionIconRadiusPx: 12,
      sectionInIconBgColor: "#ffffff14",
      sectionInIconColor: "#ff8f6b",
      sectionInIconBorderColor: "#ffffff2b",
      sectionInIconRadiusPx: 10,
      // Frosted glass buttons that fill with the accent on hover
      buttonStyle: "solid",
      buttonShape: "rounded",
      buttonBgColor: "#ffffff1a",
      buttonBgColorTo: "#ffffff0d",
      buttonTextColor: "#ffffff",
      buttonBorderColor: "#ffffff33",
      buttonHoverBgColor: "#ff8f6b",
      buttonHoverTextColor: "#2a0f06",
      buttonHoverBorderColor: "#ff8f6b",
      buttonRadiusPx: 16,
      buttonFontSize: 15,
      buttonFontWeight: 600,
      buttonPaddingX: 15,
      buttonPaddingY: 15,
      iconBgColor: "#ffffff1f",
      iconColor: "#ff8f6b",
      iconBorderColor: "#ffffff33",
      iconRadiusPx: 12,
      profilePicRadius: 999,
    }),
  },
  {
    id: "nocturne-hero",
    name: "Nocturne",
    description: "Moody evening hero with violet accents and glassy, elevated buttons.",
    settings: createTemplate({
      header_layout: "banner",
      cover_image: "https://images.unsplash.com/photo-1535007813616-79dc02ba4021?w=1600&q=80",
      bg_style: "image",
      bg_image: "https://images.unsplash.com/photo-1535007813616-79dc02ba4021?w=1600&q=80",
      bg_image_opacity: 0.7,
      heading_color: "#ffffff",
      text_color: "#d7d2e0",
      fontFamily: "spaceGrotesk",
      sectionHeaderFontSize: 25,
      sectionHeaderFontWeight: 600,
      // Frosted glass panels with soft depth
      glassBlur: 12,
      sectionShadow: "soft",
      buttonShadow: "medium",
      sectionStyle: "solid",
      sectionShape: "rounded",
      sectionBgColor: "#ffffff14",
      sectionBgColorTo: "#ffffff14",
      sectionBorderColor: "#ffffff2b",
      sectionRadiusPx: 18,
      sectionPaddingX: 22,
      sectionPaddingY: 18,
      sectionItemHeadingColor: "#ffffff",
      sectionItemTextColor: "#d7d2e0",
      sectionItemHeadingFontSize: 15,
      sectionItemHeadingFontWeight: 600,
      sectionItemTextFontSize: 13,
      sectionItemTextFontWeight: 400,
      sectionIconBgColor: "#b794f6",
      sectionIconColor: "#1a0b33",
      sectionIconBorderColor: "#b794f6",
      sectionIconRadiusPx: 12,
      sectionInIconBgColor: "#ffffff14",
      sectionInIconColor: "#b794f6",
      sectionInIconBorderColor: "#ffffff2b",
      sectionInIconRadiusPx: 10,
      // Frosted glass buttons that fill with the accent on hover
      buttonStyle: "solid",
      buttonShape: "rounded",
      buttonBgColor: "#ffffff1a",
      buttonBgColorTo: "#ffffff0d",
      buttonTextColor: "#ffffff",
      buttonBorderColor: "#ffffff33",
      buttonHoverBgColor: "#b794f6",
      buttonHoverTextColor: "#1a0b33",
      buttonHoverBorderColor: "#b794f6",
      buttonRadiusPx: 14,
      buttonFontSize: 15,
      buttonFontWeight: 600,
      buttonPaddingX: 15,
      buttonPaddingY: 15,
      iconBgColor: "#ffffff1f",
      iconColor: "#b794f6",
      iconBorderColor: "#ffffff33",
      iconRadiusPx: 12,
      profilePicRadius: 999,
    }),
  },
  {
    id: "dolce-hero",
    name: "Dolce",
    description: "Warm dessert-toned hero with amber accents and an elegant serif headline.",
    settings: createTemplate({
      header_layout: "banner",
      cover_image: "https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=1600&q=80",
      bg_style: "image",
      bg_image: "https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=1600&q=80",
      bg_image_opacity: 0.7,
      heading_color: "#ffffff",
      text_color: "#e8ded2",
      fontFamily: "manrope",
      alternative_title_font: "lora",
      sectionHeaderFontSize: 24,
      sectionHeaderFontWeight: 600,
      // Frosted glass panels with soft depth
      glassBlur: 12,
      sectionShadow: "soft",
      buttonShadow: "medium",
      sectionStyle: "solid",
      sectionShape: "pill",
      sectionBgColor: "#ffffff14",
      sectionBgColorTo: "#ffffff14",
      sectionBorderColor: "#ffffff2b",
      sectionRadiusPx: 18,
      sectionPaddingX: 22,
      sectionPaddingY: 18,
      sectionItemHeadingColor: "#ffffff",
      sectionItemTextColor: "#e8ded2",
      sectionItemHeadingFontSize: 15,
      sectionItemHeadingFontWeight: 600,
      sectionItemTextFontSize: 13,
      sectionItemTextFontWeight: 400,
      sectionIconBgColor: "#f0a95c",
      sectionIconColor: "#241300",
      sectionIconBorderColor: "#f0a95c",
      sectionIconRadiusPx: 12,
      sectionInIconBgColor: "#ffffff14",
      sectionInIconColor: "#f0a95c",
      sectionInIconBorderColor: "#ffffff2b",
      sectionInIconRadiusPx: 10,
      // Frosted glass buttons that fill with the accent on hover
      buttonStyle: "solid",
      buttonShape: "pill",
      buttonBgColor: "#ffffff1a",
      buttonBgColorTo: "#ffffff0d",
      buttonTextColor: "#ffffff",
      buttonBorderColor: "#ffffff33",
      buttonHoverBgColor: "#f0a95c",
      buttonHoverTextColor: "#241300",
      buttonHoverBorderColor: "#f0a95c",
      buttonRadiusPx: 16,
      buttonFontSize: 15,
      buttonFontWeight: 600,
      buttonPaddingX: 15,
      buttonPaddingY: 15,
      iconBgColor: "#ffffff1f",
      iconColor: "#f0a95c",
      iconBorderColor: "#ffffff33",
      iconRadiusPx: 12,
      profilePicRadius: 999,
    }),
  },
  {
    id: "verdant-hero",
    name: "Verdant",
    description: "Fresh, garden-toned hero with mint accents and clean frosted glass.",
    settings: createTemplate({
      header_layout: "banner",
      cover_image: "https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=1600&q=80",
      bg_style: "image",
      bg_image: "https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=1600&q=80",
      bg_image_opacity: 0.62,
      heading_color: "#ffffff",
      text_color: "#dfe8e2",
      fontFamily: "manrope",
      sectionHeaderFontSize: 24,
      sectionHeaderFontWeight: 600,
      // Frosted glass panels with soft depth
      glassBlur: 12,
      sectionShadow: "soft",
      buttonShadow: "medium",
      sectionStyle: "solid",
      sectionShape: "rounded",
      sectionBgColor: "#ffffff14",
      sectionBgColorTo: "#ffffff14",
      sectionBorderColor: "#ffffff2b",
      sectionRadiusPx: 18,
      sectionPaddingX: 22,
      sectionPaddingY: 18,
      sectionItemHeadingColor: "#ffffff",
      sectionItemTextColor: "#dfe8e2",
      sectionItemHeadingFontSize: 15,
      sectionItemHeadingFontWeight: 600,
      sectionItemTextFontSize: 13,
      sectionItemTextFontWeight: 400,
      sectionIconBgColor: "#7bd8a4",
      sectionIconColor: "#06251a",
      sectionIconBorderColor: "#7bd8a4",
      sectionIconRadiusPx: 12,
      sectionInIconBgColor: "#ffffff14",
      sectionInIconColor: "#7bd8a4",
      sectionInIconBorderColor: "#ffffff2b",
      sectionInIconRadiusPx: 10,
      // Frosted glass buttons that fill with the accent on hover
      buttonStyle: "solid",
      buttonShape: "rounded",
      buttonBgColor: "#ffffff1a",
      buttonBgColorTo: "#ffffff0d",
      buttonTextColor: "#ffffff",
      buttonBorderColor: "#ffffff33",
      buttonHoverBgColor: "#7bd8a4",
      buttonHoverTextColor: "#06251a",
      buttonHoverBorderColor: "#7bd8a4",
      buttonRadiusPx: 16,
      buttonFontSize: 15,
      buttonFontWeight: 600,
      buttonPaddingX: 15,
      buttonPaddingY: 15,
      iconBgColor: "#ffffff1f",
      iconColor: "#7bd8a4",
      iconBorderColor: "#ffffff33",
      iconRadiusPx: 12,
      profilePicRadius: 999,
    }),
  },
  {
    id: "aurora-gradient",
    name: "Aurora",
    description: "Electric blue-to-violet gradient with frosted glass and a cyan accent.",
    settings: createTemplate({
      header_layout: "classic",
      bg_style: "gradient",
      bg_gradient: {
        from: "#4776E6",
        to: "#8E54E9",
        direction: "to-br",
      },
      bg_color: "#4776E6",
      heading_color: "#ffffff",
      text_color: "#dbe4ff",
      fontFamily: "manrope",
      sectionHeaderFontSize: 24,
      sectionHeaderFontWeight: 700,
      // Frosted glass with soft depth over a vivid gradient
      glassBlur: 12,
      sectionShadow: "soft",
      buttonShadow: "medium",
      sectionStyle: "solid",
      sectionShape: "rounded",
      sectionBgColor: "#ffffff17",
      sectionBgColorTo: "#ffffff08",
      sectionBorderColor: "#ffffff2e",
      sectionRadiusPx: 18,
      sectionPaddingX: 22,
      sectionPaddingY: 18,
      sectionItemHeadingColor: "#ffffff",
      sectionItemTextColor: "#dbe4ff",
      sectionItemHeadingFontSize: 15,
      sectionItemHeadingFontWeight: 600,
      sectionItemTextFontSize: 13,
      sectionItemTextFontWeight: 400,
      sectionIconBgColor: "#a5f3fc",
      sectionIconColor: "#0b2540",
      sectionIconBorderColor: "#a5f3fc",
      sectionIconRadiusPx: 12,
      sectionInIconBgColor: "#ffffff14",
      sectionInIconColor: "#a5f3fc",
      sectionInIconBorderColor: "#ffffff2e",
      sectionInIconRadiusPx: 10,
      // Frosted glass buttons that fill with the accent on hover
      buttonStyle: "solid",
      buttonShape: "rounded",
      buttonBgColor: "#ffffff1a",
      buttonBgColorTo: "#ffffff0d",
      buttonTextColor: "#ffffff",
      buttonBorderColor: "#ffffff33",
      buttonHoverBgColor: "#a5f3fc",
      buttonHoverTextColor: "#0b2540",
      buttonHoverBorderColor: "#a5f3fc",
      buttonRadiusPx: 16,
      buttonFontSize: 15,
      buttonFontWeight: 600,
      buttonPaddingX: 15,
      buttonPaddingY: 15,
      iconBgColor: "#ffffff1f",
      iconColor: "#a5f3fc",
      iconBorderColor: "#ffffff33",
      iconRadiusPx: 12,
      profilePicRadius: 999,
    }),
  },
  {
    id: "sunset-gradient",
    name: "Sunset",
    description: "Warm orange-to-magenta gradient with frosted glass and a gold accent.",
    settings: createTemplate({
      header_layout: "classic",
      bg_style: "gradient",
      bg_gradient: {
        from: "#ff512f",
        to: "#dd2476",
        direction: "to-br",
      },
      bg_color: "#ff512f",
      heading_color: "#ffffff",
      text_color: "#ffe4d6",
      fontFamily: "poppins",
      sectionHeaderFontSize: 24,
      sectionHeaderFontWeight: 700,
      // Frosted glass with soft depth over a vivid gradient
      glassBlur: 12,
      sectionShadow: "soft",
      buttonShadow: "medium",
      sectionStyle: "solid",
      sectionShape: "pill",
      sectionBgColor: "#ffffff17",
      sectionBgColorTo: "#ffffff08",
      sectionBorderColor: "#ffffff2e",
      sectionRadiusPx: 18,
      sectionPaddingX: 22,
      sectionPaddingY: 18,
      sectionItemHeadingColor: "#ffffff",
      sectionItemTextColor: "#ffe4d6",
      sectionItemHeadingFontSize: 15,
      sectionItemHeadingFontWeight: 600,
      sectionItemTextFontSize: 13,
      sectionItemTextFontWeight: 400,
      sectionIconBgColor: "#ffe08a",
      sectionIconColor: "#3a0d1e",
      sectionIconBorderColor: "#ffe08a",
      sectionIconRadiusPx: 12,
      sectionInIconBgColor: "#ffffff14",
      sectionInIconColor: "#ffe08a",
      sectionInIconBorderColor: "#ffffff2e",
      sectionInIconRadiusPx: 10,
      // Frosted glass buttons that fill with the accent on hover
      buttonStyle: "solid",
      buttonShape: "pill",
      buttonBgColor: "#ffffff1a",
      buttonBgColorTo: "#ffffff0d",
      buttonTextColor: "#ffffff",
      buttonBorderColor: "#ffffff33",
      buttonHoverBgColor: "#ffe08a",
      buttonHoverTextColor: "#3a0d1e",
      buttonHoverBorderColor: "#ffe08a",
      buttonRadiusPx: 18,
      buttonFontSize: 15,
      buttonFontWeight: 600,
      buttonPaddingX: 15,
      buttonPaddingY: 15,
      iconBgColor: "#ffffff1f",
      iconColor: "#ffe08a",
      iconBorderColor: "#ffffff33",
      iconRadiusPx: 12,
      profilePicRadius: 999,
    }),
  },
  {
    id: "lagoon-gradient",
    name: "Lagoon",
    description: "Deep teal-to-indigo gradient with frosted glass and an aqua accent.",
    settings: createTemplate({
      header_layout: "classic",
      bg_style: "gradient",
      bg_gradient: {
        from: "#0f766e",
        to: "#1e3a8a",
        direction: "to-br",
      },
      bg_color: "#0f766e",
      heading_color: "#ffffff",
      text_color: "#d0f0ea",
      fontFamily: "manrope",
      sectionHeaderFontSize: 24,
      sectionHeaderFontWeight: 700,
      // Frosted glass with soft depth over a vivid gradient
      glassBlur: 12,
      sectionShadow: "soft",
      buttonShadow: "medium",
      sectionStyle: "solid",
      sectionShape: "rounded",
      sectionBgColor: "#ffffff17",
      sectionBgColorTo: "#ffffff08",
      sectionBorderColor: "#ffffff2e",
      sectionRadiusPx: 18,
      sectionPaddingX: 22,
      sectionPaddingY: 18,
      sectionItemHeadingColor: "#ffffff",
      sectionItemTextColor: "#d0f0ea",
      sectionItemHeadingFontSize: 15,
      sectionItemHeadingFontWeight: 600,
      sectionItemTextFontSize: 13,
      sectionItemTextFontWeight: 400,
      sectionIconBgColor: "#5eead4",
      sectionIconColor: "#06251f",
      sectionIconBorderColor: "#5eead4",
      sectionIconRadiusPx: 12,
      sectionInIconBgColor: "#ffffff14",
      sectionInIconColor: "#5eead4",
      sectionInIconBorderColor: "#ffffff2e",
      sectionInIconRadiusPx: 10,
      // Frosted glass buttons that fill with the accent on hover
      buttonStyle: "solid",
      buttonShape: "rounded",
      buttonBgColor: "#ffffff1a",
      buttonBgColorTo: "#ffffff0d",
      buttonTextColor: "#ffffff",
      buttonBorderColor: "#ffffff33",
      buttonHoverBgColor: "#5eead4",
      buttonHoverTextColor: "#06251f",
      buttonHoverBorderColor: "#5eead4",
      buttonRadiusPx: 16,
      buttonFontSize: 15,
      buttonFontWeight: 600,
      buttonPaddingX: 15,
      buttonPaddingY: 15,
      iconBgColor: "#ffffff1f",
      iconColor: "#5eead4",
      iconBorderColor: "#ffffff33",
      iconRadiusPx: 12,
      profilePicRadius: 999,
    }),
  },
  {
    id: "sublime-gradient",
    name: "Sublime",
    description: "Purple-to-teal gradient with frosted glass and a soft fuchsia accent.",
    settings: createTemplate({
      header_layout: "classic",
      bg_style: "gradient",
      bg_gradient: {
        from: "#360033",
        to: "#0b8793",
        direction: "to-br",
      },
      bg_color: "#360033",
      heading_color: "#ffffff",
      text_color: "#ecd9f5",
      fontFamily: "spaceGrotesk",
      sectionHeaderFontSize: 24,
      sectionHeaderFontWeight: 700,
      // Frosted glass with soft depth over a vivid gradient
      glassBlur: 12,
      sectionShadow: "soft",
      buttonShadow: "medium",
      sectionStyle: "solid",
      sectionShape: "rounded",
      sectionBgColor: "#ffffff17",
      sectionBgColorTo: "#ffffff08",
      sectionBorderColor: "#ffffff2e",
      sectionRadiusPx: 18,
      sectionPaddingX: 22,
      sectionPaddingY: 18,
      sectionItemHeadingColor: "#ffffff",
      sectionItemTextColor: "#ecd9f5",
      sectionItemHeadingFontSize: 15,
      sectionItemHeadingFontWeight: 600,
      sectionItemTextFontSize: 13,
      sectionItemTextFontWeight: 400,
      sectionIconBgColor: "#f5d0fe",
      sectionIconColor: "#2a0033",
      sectionIconBorderColor: "#f5d0fe",
      sectionIconRadiusPx: 12,
      sectionInIconBgColor: "#ffffff14",
      sectionInIconColor: "#f5d0fe",
      sectionInIconBorderColor: "#ffffff2e",
      sectionInIconRadiusPx: 10,
      // Frosted glass buttons that fill with the accent on hover
      buttonStyle: "solid",
      buttonShape: "rounded",
      buttonBgColor: "#ffffff1a",
      buttonBgColorTo: "#ffffff0d",
      buttonTextColor: "#ffffff",
      buttonBorderColor: "#ffffff33",
      buttonHoverBgColor: "#f5d0fe",
      buttonHoverTextColor: "#2a0033",
      buttonHoverBorderColor: "#f5d0fe",
      buttonRadiusPx: 14,
      buttonFontSize: 15,
      buttonFontWeight: 600,
      buttonPaddingX: 15,
      buttonPaddingY: 15,
      iconBgColor: "#ffffff1f",
      iconColor: "#f5d0fe",
      iconBorderColor: "#ffffff33",
      iconRadiusPx: 12,
      profilePicRadius: 999,
    }),
  },
  {
    id: "blossom-gradient",
    name: "Blossom",
    description: "Plum-to-coral gradient with frosted glass, a peach accent and a serif headline.",
    settings: createTemplate({
      header_layout: "classic",
      bg_style: "gradient",
      bg_gradient: {
        from: "#8e2c6d",
        to: "#f15f79",
        direction: "to-br",
      },
      bg_color: "#8e2c6d",
      heading_color: "#ffffff",
      text_color: "#ffe0ea",
      fontFamily: "manrope",
      alternative_title_font: "playfair",
      sectionHeaderFontSize: 25,
      sectionHeaderFontWeight: 600,
      // Frosted glass with soft depth over a vivid gradient
      glassBlur: 12,
      sectionShadow: "soft",
      buttonShadow: "medium",
      sectionStyle: "solid",
      sectionShape: "pill",
      sectionBgColor: "#ffffff17",
      sectionBgColorTo: "#ffffff08",
      sectionBorderColor: "#ffffff2e",
      sectionRadiusPx: 18,
      sectionPaddingX: 22,
      sectionPaddingY: 18,
      sectionItemHeadingColor: "#ffffff",
      sectionItemTextColor: "#ffe0ea",
      sectionItemHeadingFontSize: 15,
      sectionItemHeadingFontWeight: 600,
      sectionItemTextFontSize: 13,
      sectionItemTextFontWeight: 400,
      sectionIconBgColor: "#ffe4c4",
      sectionIconColor: "#3a1226",
      sectionIconBorderColor: "#ffe4c4",
      sectionIconRadiusPx: 12,
      sectionInIconBgColor: "#ffffff14",
      sectionInIconColor: "#ffe4c4",
      sectionInIconBorderColor: "#ffffff2e",
      sectionInIconRadiusPx: 10,
      // Frosted glass buttons that fill with the accent on hover
      buttonStyle: "solid",
      buttonShape: "pill",
      buttonBgColor: "#ffffff1a",
      buttonBgColorTo: "#ffffff0d",
      buttonTextColor: "#ffffff",
      buttonBorderColor: "#ffffff33",
      buttonHoverBgColor: "#ffe4c4",
      buttonHoverTextColor: "#3a1226",
      buttonHoverBorderColor: "#ffe4c4",
      buttonRadiusPx: 18,
      buttonFontSize: 15,
      buttonFontWeight: 600,
      buttonPaddingX: 15,
      buttonPaddingY: 15,
      iconBgColor: "#ffffff1f",
      iconColor: "#ffe4c4",
      iconBorderColor: "#ffffff33",
      iconRadiusPx: 12,
      profilePicRadius: 999,
    }),
  },
  {
    id: "glassmorphism",
    name: "Glassmorphism",
    description: "Frosted glass panels with soft blur and vibrant accents.",
    settings: createTemplate({
      bg_style: "gradient",
      bg_gradient: {
        from: "#1a1a2e",
        to: "#16213e",
        direction: "to-br",
      },
      bg_color: "#1a1a2e",
      heading_color: "#ffffff",
      text_color: "#b0b0b0",
      fontFamily: "inter",
      sectionBgColor: "#ffffff33",
      sectionBgColorTo: "#ffffff0d",
      sectionStyle: "gradient",
      sectionBorderColor: "#ffffff33",
      sectionItemHeadingColor: "#ffffff",
      sectionItemTextColor: "#b0b0b0",
      buttonStyle: "solid",
      buttonBgColor: "#ffffff33",
      buttonBgColorTo: "#ffffff11",
      buttonTextColor: "#ffffff",
      buttonBorderColor: "#ffffff44",
      buttonHoverBgColor: "#ffffff55",
      buttonHoverTextColor: "#ffffff",
      buttonHoverBorderColor: "#ffffff66",
      buttonRadiusPx: 16,
      buttonShape: "pill",
      sectionRadiusPx: 24,
      sectionShape: "pill",
      sectionPaddingX: 24,
      sectionPaddingY: 20,
      sectionIconBgColor: "#ffffff22",
      sectionIconBorderColor: "#ffffff44",
      sectionIconRadiusPx: 16,
      sectionIconColor: "#ffffff",
      iconBgColor: "#ffffff22",
      iconColor: "#ffffff",
      iconBorderColor: "#ffffff44",
      iconRadiusPx: 16,
      sectionInIconBgColor: "transparent",
      sectionInIconBorderColor: "#ffffff44",
      sectionInIconRadiusPx: 16,
      sectionInIconColor: "#ffffff",
    }),
  },
  {
    id: "minimal-light",
    name: "Minimal Light",
    description: "Clean, airy, and modern with soft grays and white.",
    settings: createTemplate({
      bg_color: "#f8f9fa",
      bg_style: "color",
      heading_color: "#1e293b",
      text_color: "#475569",
      fontFamily: "inter",
      sectionBgColor: "#ffffff",
      sectionBorderColor: "#e2e8f0",
      buttonStyle: "solid",
      buttonBgColor: "#0f172a",
      buttonTextColor: "#ffffff",
      buttonBorderColor: "#0f172a",
      buttonHoverBgColor: "#1e293b",
      buttonHoverTextColor: "#ffffff",
      buttonHoverBorderColor: "#1e293b",
      buttonRadiusPx: 8,
      buttonShape: "rounded",
      sectionRadiusPx: 12,
      sectionShape: "rounded",
      sectionPaddingX: 20,
      sectionPaddingY: 16,
      iconBgColor: "#f1f5f9",
      iconColor: "#0f172a",
      iconBorderColor: "#e2e8f0",
      iconRadiusPx: 8,
      sectionIconBgColor: "#0f172a",
      sectionIconColor: "#ffffff",
      sectionIconBorderColor: "#ffffff",
      sectionItemHeadingColor: "#000000",
      sectionItemTextColor: "#475569",
      sectionInIconColor: "#000000",
    }),
  },
  {
    id: "dark-elegance",
    name: "Dark Elegance",
    description: "Deep charcoal with gold accents and a serif font.",
    settings: createTemplate({
      bg_color: "#121212",
      bg_style: "color",
      heading_color: "#f5e6d3",
      text_color: "#cfc5b9",
      fontFamily: "playfair",
      alternative_title_font: "merriweather",
      sectionBgColor: "#1e1e1e",
      sectionBorderColor: "#d4af37",
      buttonStyle: "outline",
      sectionItemHeadingColor: "#d4af37",
      sectionItemTextColor: "#cfc5b9",
      buttonBgColor: "transparent",
      buttonTextColor: "#d4af37",
      buttonBorderColor: "#d4af37",
      buttonHoverBgColor: "#d4af37",
      buttonHoverTextColor: "#121212",
      buttonHoverBorderColor: "#d4af37",
      buttonRadiusPx: 4,
      buttonShape: "square",
      sectionRadiusPx: 4,
      sectionShape: "square",
      sectionPaddingX: 24,
      sectionPaddingY: 20,
      iconBgColor: "#2a2a2a",
      iconColor: "#d4af37",
      iconBorderColor: "#d4af37",
      iconRadiusPx: 4,
      sectionIconColor: "#d4af37",
      sectionIconBgColor: "#2a2a2a",
      sectionIconBorderColor: "#d4af37",
      sectionInIconBgColor: "transparent",
      sectionInIconBorderColor: "transparent",
      sectionInIconRadiusPx: 7,
      sectionInIconColor: "#ffffff",
      sectionStyle: "outline",
    }),
  },
  {
    id: "warm-organic",
    name: "Warm Organic",
    description: "Earthy terracotta, olive, and warm beige tones.",
    settings: createTemplate({
      bg_color: "#f4ece2",
      bg_style: "color",
      heading_color: "#5c4033",
      text_color: "#7a5a4a",
      fontFamily: "lora",
      alternative_title_font: "dmSerif",
      sectionBgColor: "#ffffffcc",
      sectionBorderColor: "#d4b8a8",
      buttonStyle: "solid",
      buttonBgColor: "#8b5a2b",
      buttonTextColor: "#f4ece2",
      buttonBorderColor: "#8b5a2b",
      buttonHoverBgColor: "#a8733a",
      buttonHoverTextColor: "#f4ece2",
      buttonHoverBorderColor: "#a8733a",
      buttonRadiusPx: 30,
      buttonShape: "pill",
      sectionRadiusPx: 16,
      sectionShape: "rounded",
      sectionPaddingX: 22,
      sectionPaddingY: 18,
      iconBgColor: "#d4b8a8",
      iconColor: "#5c4033",
      iconBorderColor: "#c4a08a",
      iconRadiusPx: 20,
      sectionInIconBgColor: "#ffffff",
      sectionInIconBorderColor: "#ffffff",
      sectionInIconRadiusPx: 7,
      sectionInIconColor: "#000000",
      sectionItemHeadingColor: "#5c4033",
      sectionItemTextColor: "#7a5a4a",
      sectionIconBgColor: "#8b5a2b",
      sectionIconColor: "#ffffff",
      sectionIconBorderColor: "#8b5a2b",
    }),
  },
  {
    id: "ocean-breeze",
    name: "Ocean Breeze",
    description: "Cool blues and teals with a fresh, coastal feel.",
    settings: createTemplate({
      bg_style: "gradient",
      bg_gradient: {
        from: "#0a1f2c",
        to: "#1b4f6e",
        direction: "to-br",
      },
      bg_color: "#0a1f2c",
      heading_color: "#e0f7fa",
      text_color: "#b2ebf2",
      fontFamily: "nunito",
      sectionBgColor: "#fcfcfc",
      sectionBgColorTo: "#00bcd4",
      sectionStyle: "solid",
      sectionBorderColor: "#596463",
      buttonStyle: "solid",
      buttonBgColor: "#00bcd4",
      buttonTextColor: "#000000",
      buttonBorderColor: "#00bcd4",
      buttonHoverBgColor: "#0097a7",
      buttonHoverTextColor: "#ffffff",
      buttonHoverBorderColor: "#0097a7",
      buttonRadiusPx: 8,
      buttonShape: "rounded",
      sectionRadiusPx: 12,
      sectionShape: "rounded",
      sectionPaddingX: 20,
      sectionPaddingY: 16,
      iconBgColor: "white",
      iconColor: "black",
      iconBorderColor: "#4dd0e1",
      iconRadiusPx: 8,
      sectionInIconBgColor: "#ffffff",
      sectionInIconBorderColor: "#ffffff",
      sectionInIconRadiusPx: 7,
      sectionInIconColor: "#000000",
      sectionIconBgColor: "#000000",
      sectionIconColor: "#ffffff",
      sectionIconBorderColor: "#00bcd4",
      sectionItemHeadingColor: "#000000",
      sectionItemTextColor: "#696969",
    }),
  },
  {
    id: "sunset-glow",
    name: "Sunset Glow",
    description: "Warm oranges, pinks, and purples like a sunset.",
    settings: createTemplate({
      bg_color: "#2d1b3d",
      bg_style: "gradient",
      iconColor: "#ff7f50",
      fontFamily: "raleway",
      text_color: "#f3eded",
      bg_gradient: {
        to: "#e65c00",
        from: "#2d1b3d",
        direction: "to-br",
      },
      buttonShape: "rounded",
      buttonStyle: "solid",
      iconBgColor: "white",
      iconRadiusPx: 12,
      sectionShape: "rounded",
      sectionStyle: "solid",
      buttonBgColor: "#ff7f50",
      header_layout: "classic",
      heading_color: "#ffffff",
      buttonFontSize: 15,
      buttonPaddingX: 11,
      buttonPaddingY: 12,
      buttonRadiusPx: 12,
      sectionBgColor: "#ffffff",
      buttonBgColorTo: "#00b83d",
      buttonTextColor: "#ffffff",
      iconBorderColor: "white",
      sectionPaddingX: 22,
      sectionPaddingY: 18,
      sectionRadiusPx: 16,
      bg_image_opacity: 0.35,
      buttonFontWeight: 600,
      profilePicRadius: 15,
      sectionBgColorTo: "#ffffff",
      sectionIconColor: "#ff7f50",
      buttonBorderColor: "#ff7f50",
      buttonHoverBgColor: "#ff6347",
      sectionBorderColor: "#ffa07a44",
      sectionIconBgColor: "white",
      sectionInIconColor: "#ffffff",
      sectionIconRadiusPx: 8,
      buttonHoverTextColor: "#ffffff",
      sectionInIconBgColor: "#ff7f50",
      sectionItemTextColor: "#525252",
      sectionHeaderFontSize: 20,
      sectionInIconRadiusPx: 7,
      alternative_title_font: "bebas",
      buttonHoverBorderColor: "#ff6347",
      sectionIconBorderColor: "white",
      sectionHeaderFontWeight: 600,
      sectionItemHeadingColor: "#000000",
      sectionItemTextFontSize: 13,
      sectionInIconBorderColor: "#ff7f50",
      sectionItemTextFontWeight: 400,
      sectionItemHeadingFontSize: 15,
      sectionItemHeadingFontWeight: 600,
    }),
  },
  {
    id: "bold-minimal",
    name: "Bold Minimal",
    description: "High contrast black and white, sharp and modern.",
    settings: createTemplate({
      bg_color: "#000000",
      bg_style: "color",
      iconColor: "#ffffff",
      fontFamily: "workSans",
      text_color: "#aaaaaa",
      bg_gradient: {
        to: "#0b0d10",
        from: "#0a1f2c",
        direction: "to-br",
      },
      buttonShape: "square",
      buttonStyle: "outline",
      iconBgColor: "#222222",
      iconRadiusPx: 0,
      sectionShape: "square",
      sectionStyle: "solid",
      buttonBgColor: "transparent",
      header_layout: "classic",
      heading_color: "#ffffff",
      buttonFontSize: 15,
      buttonPaddingX: 11,
      buttonPaddingY: 12,
      buttonRadiusPx: 0,
      sectionBgColor: "#111111",
      buttonBgColorTo: "#00b83d",
      buttonTextColor: "#ffffff",
      iconBorderColor: "#333333",
      sectionPaddingX: 16,
      sectionPaddingY: 12,
      sectionRadiusPx: 0,
      bg_image_opacity: 0.35,
      buttonFontWeight: 600,
      profilePicRadius: 0,
      sectionBgColorTo: "#2563eb",
      sectionIconColor: "#ffffff",
      buttonBorderColor: "#333333",
      buttonHoverBgColor: "#ffffff",
      sectionBorderColor: "#333333",
      sectionIconBgColor: "#222222",
      sectionInIconColor: "#ffffff",
      sectionIconRadiusPx: 0,
      buttonHoverTextColor: "#000000",
      sectionInIconBgColor: "#ffffff22",
      sectionItemTextColor: "#aaaaaa",
      sectionHeaderFontSize: 20,
      sectionInIconRadiusPx: 16,
      alternative_title_font: "bebas",
      buttonHoverBorderColor: "#ffffff",
      sectionIconBorderColor: "#333333",
      sectionHeaderFontWeight: 600,
      sectionItemHeadingColor: "#ffffff",
      sectionItemTextFontSize: 13,
      sectionInIconBorderColor: "#ffffff44",
      sectionItemTextFontWeight: 400,
      sectionItemHeadingFontSize: 15,
      sectionItemHeadingFontWeight: 600,
    }),
  },
  {
    id: "green",
    name: "Green",
    description: "Earthy green theme with solid sections and white buttons.",
    settings: createTemplate({
      bg_color: "#0e2e2e",
      bg_style: "color",
      iconColor: "#000000",
      fontFamily: "poppins",
      text_color: "#d1d1d1",
      bg_gradient: {
        to: "#0b0d10",
        from: "#0a1f2c",
        direction: "to-br",
      },
      buttonShape: "square",
      buttonStyle: "solid",
      iconBgColor: "#ffffff",
      iconRadiusPx: 0,
      sectionShape: "square",
      sectionStyle: "solid",
      buttonBgColor: "#ffffff",
      header_layout: "classic",
      heading_color: "#ffffff",
      buttonFontSize: 16,
      buttonPaddingX: 10,
      buttonPaddingY: 10,
      buttonRadiusPx: 0,
      sectionBgColor: "#ffffff",
      buttonBgColorTo: "#00b83d",
      buttonTextColor: "#022c22e6",
      iconBorderColor: "#022c22e6",
      sectionPaddingX: 10,
      sectionPaddingY: 10,
      sectionRadiusPx: 0,
      bg_image_opacity: 0.35,
      buttonFontWeight: 600,
      profilePicRadius: 0,
      sectionBgColorTo: "#2563eb",
      sectionIconColor: "#ffffff",
      buttonBorderColor: "#022c22e6",
      buttonHoverBgColor: "#ffffff",
      sectionBorderColor: "#999999",
      sectionIconBgColor: "#022c22e6",
      sectionInIconColor: "#000000",
      sectionIconRadiusPx: 0,
      buttonHoverTextColor: "#000000",
      sectionInIconBgColor: "#ffffff",
      sectionItemTextColor: "#434242",
      sectionHeaderFontSize: 20,
      sectionInIconRadiusPx: 0,
      alternative_title_font: "poppins",
      buttonHoverBorderColor: "#c7c6c6",
      sectionIconBorderColor: "#ffffff",
      sectionHeaderFontWeight: 600,
      sectionItemHeadingColor: "#000000",
      sectionItemTextFontSize: 14,
      sectionInIconBorderColor: "#ffffff",
      sectionItemTextFontWeight: 400,
      sectionItemHeadingFontSize: 16,
      sectionItemHeadingFontWeight: 600,
    }),
  },
  {
    id: "crimson-bold",
    name: "Crimson Bold",
    description: "High‑impact red and black, sharp edges, solid and striking.",
    settings: createTemplate({
      bg_color: "#1a0000",
      bg_style: "color",
      iconColor: "#ff3333",
      fontFamily: "montserrat",
      text_color: "#dedede",
      bg_gradient: {
        to: "#0b0d10",
        from: "#0a1f2c",
        direction: "to-br",
      },
      buttonShape: "square",
      buttonStyle: "solid",
      iconBgColor: "#fffafa",
      iconRadiusPx: 0,
      sectionShape: "square",
      sectionStyle: "solid",
      buttonBgColor: "#cc0000",
      header_layout: "classic",
      heading_color: "#ffffff",
      buttonFontSize: 15,
      buttonPaddingX: 11,
      buttonPaddingY: 12,
      buttonRadiusPx: 0,
      sectionBgColor: "#2a0000",
      buttonBgColorTo: "#00b83d",
      buttonTextColor: "#ffffff",
      iconBorderColor: "#cc0000",
      sectionPaddingX: 16,
      sectionPaddingY: 12,
      sectionRadiusPx: 0,
      bg_image_opacity: 0.35,
      buttonFontWeight: 600,
      profilePicRadius: 15,
      sectionBgColorTo: "#2563eb",
      sectionIconColor: "#ff3333",
      buttonBorderColor: "#cc0000",
      buttonHoverBgColor: "#ff0000",
      sectionBorderColor: "#ff3333",
      sectionIconBgColor: "#ffffff",
      sectionInIconColor: "#fff5f5",
      sectionIconRadiusPx: 0,
      buttonHoverTextColor: "#ffffff",
      sectionInIconBgColor: "#2a0000",
      sectionItemTextColor: "#d1d1d1",
      sectionHeaderFontSize: 20,
      sectionInIconRadiusPx: 0,
      alternative_title_font: "bebas",
      buttonHoverBorderColor: "#ff0000",
      sectionIconBorderColor: "#cc0000",
      sectionHeaderFontWeight: 600,
      sectionItemHeadingColor: "#ffffff",
      sectionItemTextFontSize: 13,
      sectionInIconBorderColor: "transparent",
      sectionItemTextFontWeight: 400,
      sectionItemHeadingFontSize: 15,
      sectionItemHeadingFontWeight: 600,
    }),
  },
  {
    id: "lavender-dream",
    name: "Lavender Dream",
    description: "Soft purples, rounded shapes, serif font, gentle and elegant.",
    settings: createTemplate({
      bg_color: "#e8d5f5",
      bg_style: "gradient",
      iconColor: "#000000",
      fontFamily: "playfair",
      text_color: "#6b4c7a",
      bg_gradient: {
        to: "#d4c0e8",
        from: "#e8d5f5",
        direction: "to-br",
      },
      buttonShape: "pill",
      buttonStyle: "solid",
      iconBgColor: "#fcfcfc",
      iconRadiusPx: 20,
      sectionShape: "pill",
      sectionStyle: "gradient",
      buttonBgColor: "#9b6bb0",
      header_layout: "classic",
      heading_color: "#4a2c5a",
      buttonFontSize: 15,
      buttonPaddingX: 11,
      buttonPaddingY: 12,
      buttonRadiusPx: 20,
      sectionBgColor: "#ffffffcc",
      buttonBgColorTo: "#00b83d",
      buttonTextColor: "#ffffff",
      iconBorderColor: "#9b6bb0",
      sectionPaddingX: 28,
      sectionPaddingY: 22,
      sectionRadiusPx: 24,
      bg_image_opacity: 0.35,
      buttonFontWeight: 600,
      profilePicRadius: 15,
      sectionBgColorTo: "#f3e8ffcc",
      sectionIconColor: "#000000",
      buttonBorderColor: "#9b6bb0",
      buttonHoverBgColor: "#7d4b94",
      sectionBorderColor: "#c4a0d0",
      sectionIconBgColor: "#ffffff",
      sectionInIconColor: "#9b6bb0",
      sectionIconRadiusPx: 16,
      buttonHoverTextColor: "#ffffff",
      sectionInIconBgColor: "transparent",
      sectionItemTextColor: "#6b4c7a",
      sectionHeaderFontSize: 20,
      sectionInIconRadiusPx: 12,
      alternative_title_font: "dmSerif",
      buttonHoverBorderColor: "#7d4b94",
      sectionIconBorderColor: "#9b6bb0",
      sectionHeaderFontWeight: 600,
      sectionItemHeadingColor: "#4a2c5a",
      sectionItemTextFontSize: 13,
      sectionInIconBorderColor: "transparent",
      sectionItemTextFontWeight: 400,
      sectionItemHeadingFontSize: 15,
      sectionItemHeadingFontWeight: 600,
    }),
  },
  {
    id: "urban-chic",
    name: "Urban Chic",
    description: "Modern urban gradient, sans‑serif, subtle and refined.",
    settings: createTemplate({
      header_layout: "classic",
      bg_style: "gradient",
      bg_gradient: {
        from: "#2c2c2c",
        to: "#1a1a1a",
        direction: "to-b",
      },
      bg_color: "#2c2c2c",
      bg_image_opacity: 0.3,
      heading_color: "#f0f0f0",
      text_color: "#cccccc",
      fontFamily: "inter",
      alternative_title_font: "manrope",
      sectionBgColor: "#222222cc",
      sectionBgColorTo: "#333333cc",
      sectionStyle: "gradient",
      sectionBorderColor: "#66666655",
      sectionItemHeadingColor: "#ffffff",
      sectionItemTextColor: "#bbbbbb",
      buttonStyle: "outline",
      buttonBgColor: "transparent",
      buttonTextColor: "#ffffff",
      buttonBorderColor: "#888888",
      buttonHoverBgColor: "#ffffff",
      buttonHoverTextColor: "#222222",
      buttonHoverBorderColor: "#ffffff",
      buttonRadiusPx: 4,
      buttonShape: "square",
      sectionRadiusPx: 8,
      sectionShape: "rounded",
      sectionPaddingX: 20,
      sectionPaddingY: 16,
      iconBgColor: "#33333366",
      iconColor: "#ffffff",
      iconBorderColor: "#666666",
      iconRadiusPx: 4,
      sectionIconBgColor: "#33333366",
      sectionIconColor: "#ffffff",
      sectionIconBorderColor: "#666666",
      sectionIconRadiusPx: 4,
      sectionInIconBgColor: "#ffffff22",
      sectionInIconColor: "#cccccc",
      sectionInIconBorderColor: "#ffffff44",
      sectionInIconRadiusPx: 4,
    }),
  },


];
